site_name: Hyperion Docs

markdown_extensions:
- admonition
- pymdownx.mark
- pymdownx.details
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- toc:
    permalink: true

google_analytics:
- UA-117919122-3
- auto

repo_name: 'eosrio/hyperion-history-api'
repo_url: 'https://github.com/eosrio/hyperion-history-api'

nav:
- Home: index.md
- Providers:
  - Hyperion Installation:
    - Manual Installation: manual_installation.md
    - Installation Script: installation_script.md
    - Docker: docker.md
  - Hyperion Set Up:
    - Configuration: hyperion_configuration.md
    - Connections Configuration: connections.md
    - Chain Configuration: chain.md
- Users / Developers:
  - Getting Started: howtouse.md
  - Stream Client: stream_client.md
  - Endpoint List: endpoint.md
- API Reference:
  - v2: v2.md
  - v1 compatible: v1.md
- Troubleshooting:
  #- Kibana: kibana.md
  - RabbitMQ: rabbit.md
#  - FAQ: faq.md

theme:
  name: 'material'
  palette:
    primary: 'light blue'
    accent: 'orange'
  logo: 'img/simplified_logo.svg'
  favicon: 'img/icon.png'
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: 'https://github.com/eosrio/hyperion-history-api'
  - icon: fontawesome/brands/twitter
    link: 'https://twitter.com/eosriobrazil'
  - icon: fontawesome/brands/telegram
    link: 'https://t.me/EOSHyperion'
