site_name: Hyperion Docs

markdown_extensions:
  - admonition
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true


google_analytics:
  - UA-117919122-3
  - auto

# Repository
repo_name: 'eosrio/hyperion-history-api'
repo_url: 'https://github.com/eosrio/hyperion-history-api'

nav:
    - Home: index.md
    - Providers:
      - Enviroment Setup:
        - Script: quickstart.md
        - Manual: install.md
        - Docker: docker.md
      - Hyperion Setup: hyperion.md
      - Connections: connections.md
      - Chain Configuration: chain.md
      - Ecosystem: ecosystem.md
    - Users / Developers:
      - Getting Started: howtouse.md
      - Stream Client: stream_client.md
      - Endpoint List: endpoint.md
    - API Reference:
        - v2: v2.md
        - v1 compatible: v1.md
    - Troubleshooting:
#      - Kibana: kibana.md
      - RabbitMQ: rabbit.md
    #  - FAQ: faq.md

#theme: readthedocs
theme:
  name: 'material'
  palette:
    primary: 'light blue'
    accent: 'orange'
  logo: 'img/simplified_logo.svg'
  favicon: 'img/icon.png'

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/eosrio/hyperion-history-api'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/eosriobrazil'
    - icon: fontawesome/brands/telegram
      link: 'https://t.me/EOSHyperion'
